repos:
  # 1. Verifica se há chaves/segredos expostos
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        name: Detectar segredos sensíveis
        args: ["--verbose"]

  # 2. Checa formatação e padrões de código (JavaScript/Node)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: Padronizar código JS/TS/JSON

  # 3. Bloqueia commits grandes demais (evita leaks massivos)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        name: Evitar arquivos grandes (>1MB) no commit
        args: ["--maxkb=1000"]

  # 4. Detecta arquivos com credenciais em texto plano (por nome)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: detect-private-key
        name: Evitar commit de chaves privadas
